name: snn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - anyio=4.2.0=py38hca03da5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h1a28f6b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py38hca03da5_0
  - attrs=24.2.0=py38hca03da5_0
  - babel=2.11.0=py38hca03da5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38hca03da5_0
  - blas=1.0=openblas
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.7=py38hbda83bc_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py38h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.8.30=hf0a4a13_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py38h3eb5a62_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py38hca03da5_0
  - contourpy=1.0.5=py38h525c30c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9131b1a_1
  - debugpy=1.6.7=py38h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py38hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - filelock=3.13.1=py38hca03da5_0
  - fonttools=4.51.0=py38h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - gettext=0.22.5=h8414b35_3
  - gettext-tools=0.22.5=h8414b35_3
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py38h8c48613_0
  - gst-plugins-base=1.14.1=h313beb8_1
  - gstreamer=1.14.1=h80987f9_1
  - h11=0.14.0=py38hca03da5_0
  - httpcore=1.0.2=py38hca03da5_0
  - httpx=0.27.0=py38hca03da5_0
  - icu=73.1=h313beb8_0
  - idna=3.7=py38hca03da5_0
  - importlib-metadata=7.0.1=py38hca03da5_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38hca03da5_0
  - ipykernel=6.29.5=py38hca03da5_0
  - ipython=8.12.2=py38hca03da5_0
  - ipywidgets=8.1.2=py38hca03da5_0
  - jedi=0.19.1=py38hca03da5_0
  - jinja2=3.1.4=py38hca03da5_0
  - jpeg=9e=h80987f9_3
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38hca03da5_0
  - jsonschema-specifications=2023.7.1=py38hca03da5_0
  - jupyter=1.0.0=py38hca03da5_9
  - jupyter-lsp=2.2.0=py38hca03da5_0
  - jupyter_client=8.6.0=py38hca03da5_0
  - jupyter_console=6.6.3=py38hca03da5_0
  - jupyter_core=5.7.2=py38hca03da5_0
  - jupyter_events=0.10.0=py38hca03da5_0
  - jupyter_server=2.14.1=py38hca03da5_0
  - jupyter_server_terminals=0.4.4=py38hca03da5_1
  - jupyterlab=4.2.5=py38hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38hca03da5_0
  - jupyterlab_widgets=3.0.10=py38hca03da5_0
  - kiwisolver=1.4.4=py38h313beb8_0
  - krb5=1.20.1=hf3e1bf2_1
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libasprintf=0.22.5=h8414b35_3
  - libasprintf-devel=0.22.5=h8414b35_3
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libclang=14.0.6=default_h1b80db6_1
  - libclang13=14.0.6=default_h24352ff_1
  - libcxx=19.1.3=ha82da77_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libflac=1.4.3=hb765f3a_0
  - libgettextpo=0.22.5=h8414b35_3
  - libgettextpo-devel=0.22.5=h8414b35_3
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.17=h0d3ecfb_2
  - libintl=0.22.5=h8414b35_3
  - libintl-devel=0.22.5=h8414b35_3
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libllvm14=14.0.6=h19fdd8a_4
  - libogg=1.3.5=h99b78c6_0
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3.1=h27ca646_1
  - libpng=1.6.39=h80987f9_0
  - libpq=12.20=h02f6b3c_0
  - libsndfile=1.2.2=h9739721_1
  - libsodium=1.0.18=h1a28f6b_0
  - libtiff=4.5.1=h313beb8_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.1=h0b34f26_2
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py38h80987f9_0
  - matplotlib=3.7.2=py38hca03da5_0
  - matplotlib-base=3.7.2=py38h46d7db6_0
  - matplotlib-inline=0.1.6=py38hca03da5_0
  - mistune=2.0.4=py38hca03da5_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpg123=1.32.9=hf642e45_0
  - mpmath=1.3.0=py38hca03da5_0
  - mysql=5.7.24=ha71a6ea_2
  - nbclient=0.8.0=py38hca03da5_0
  - nbconvert=7.16.4=py38hca03da5_0
  - nbformat=5.10.4=py38hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py38hca03da5_0
  - networkx=3.1=py38hca03da5_0
  - notebook=7.2.2=py38hca03da5_1
  - notebook-shim=0.2.3=py38hca03da5_0
  - numexpr=2.8.4=py38h79ee842_1
  - numpy=1.24.3=py38h1398885_0
  - numpy-base=1.24.3=py38h90707a3_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.4.0=h39f12f2_0
  - overrides=7.4.0=py38hca03da5_0
  - packaging=24.1=py38hca03da5_0
  - pandas=2.0.3=py38h46d7db6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hb066dcc_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h80987f9_0
  - pip=24.2=py38hca03da5_0
  - pkgutil-resolve-name=1.3.10=py38hca03da5_1
  - platformdirs=3.10.0=py38hca03da5_0
  - ply=3.11=py38hca03da5_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py38hca03da5_0
  - prompt-toolkit=3.0.43=py38hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py38h1a28f6b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38hca03da5_1
  - pyparsing=3.0.9=py38hca03da5_0
  - pyqt=5.15.10=py38h313beb8_0
  - pyqt5-sip=12.13.0=py38h80987f9_0
  - pysocks=1.7.1=py38hca03da5_0
  - pysoundfile=0.12.1=pyhd8ed1ab_0
  - python=3.8.20=hb885b13_0
  - python-dateutil=2.9.0post0=py38hca03da5_2
  - python-fastjsonschema=2.16.2=py38hca03da5_0
  - python-json-logger=2.0.7=py38hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.4.1=py3.8_0
  - pytz=2024.1=py38hca03da5_0
  - pyyaml=6.0.2=py38h80987f9_0
  - pyzmq=25.1.2=py38h313beb8_0
  - qt-main=5.15.2=h0917680_10
  - qtconsole=5.6.0=py38hca03da5_0
  - qtpy=2.4.1=py38hca03da5_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py38hca03da5_0
  - requests=2.32.3=py38hca03da5_0
  - rfc3339-validator=0.1.4=py38hca03da5_0
  - rfc3986-validator=0.1.1=py38hca03da5_0
  - rpds-py=0.10.6=py38hf0e4da2_0
  - scipy=1.10.1=py38h9d039d2_1
  - send2trash=1.8.2=py38hca03da5_0
  - setuptools=75.1.0=py38hca03da5_0
  - sip=6.7.12=py38h313beb8_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py38hca03da5_0
  - soupsieve=2.5=py38hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.2=py38hca03da5_0
  - terminado=0.17.1=py38hca03da5_0
  - tinycss2=1.2.1=py38hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tomli=2.0.1=py38hca03da5_0
  - torchaudio=2.4.1=py38_cpu
  - torchvision=0.20.0=py38_cpu
  - tornado=6.4.1=py38h80987f9_0
  - traitlets=5.14.3=py38hca03da5_0
  - typing-extensions=4.11.0=py38hca03da5_0
  - typing_extensions=4.11.0=py38hca03da5_0
  - unicodedata2=15.1.0=py38h80987f9_0
  - urllib3=2.2.3=py38hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - websocket-client=1.8.0=py38hca03da5_0
  - wfdb=4.1.2=pyhd8ed1ab_0
  - wheel=0.44.0=py38hca03da5_0
  - widgetsnbextension=4.0.10=py38hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.20.2=py38hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - fsspec==2024.10.0
      - tqdm==4.67.0
prefix: /Users/ww/anaconda3/envs/snn
